#!/bin/bash

verde="\033[1;32m"
magenta="\033[0;35m"
rescolor="\e[0m"
amarillo="\033[1;33m"
azul="\033[1;34m"
SP="            "

SYSTEM_PRODUT_NAME=$(sudo dmidecode -s system-product-name)
SYSTEM_SERIAL_NUMBER=$(sudo dmidecode -s system-serial-number)
CHASSIS_MANUFACTURE=$(sudo dmidecode -s chassis-manufacturer)
CHASSIS_SERIAL_NUMBER=$(sudo dmidecode -s chassis-serial-number)
MONITOR_INFO=$(hwinfo --short --monitor)
MONITOR_SERIAL=$(hwinfo --monitor 2>/dev/null | grep "Serial ID:" | head -1 | cut -d":" -f2)
MEMORY_INFO=$(hwinfo --short --memory)
MEMORY_ID=$(hwinfo --memory 2>/dev/null | grep "Unique ID:" | head -1 | cut -d":" -f2)
MEMORY_RANGE=$(hwinfo --memory 2>/dev/null | grep "Memory Range:" | head -1 | cut -d":" -f2)
MEMORY_SIZE=$(hwinfo --memory 2>/dev/null | grep "Memory Size:" | head -1 | cut -d":" -f2)

function getInfoSystem(){
	echo -e $azul"---INICIANDO ECANER SYSTEM......"$rescolor
	echo -e $verde"<.;** HECHO **;.>"$rescolor
	sudo echo "

	$( echo "#---------------INFO SYSTEM-----------------#" && echo "$SP PRODUCTO NAME: "$SYSTEM_PRODUT_NAME && echo "$SP NUMERO SERIAL: "$SYSTEM_SERIAL_NUMBER  && echo )

	$( echo "#---------------INFO CHASSIS----------------#" && echo "$SP MANUFACTURER: "$CHASSIS_MANUFACTURE && echo "$SP NUMERO SERIAL: "$CHASSIS_SERIAL_NUMBER  && echo )

	$( echo "#---------------INFO MONITOR----------------#" && echo "$SP "$MONITOR_INFO && echo "$SP NUMERO SERIAL: "$MONITOR_SERIAL  && echo )
	
	$( echo "#---------------INFO MEMORY----------------#" && echo  "$SP "$MEMORY_INFO  && echo "$SP Unique ID: "$MEMORY_ID && echo "$SP Memory Range: "$MEMORY_RANGE && echo "$SP Memory Size: "$MEMORY_SIZE  && echo )
		
	">$PWD"/MAQUINE-[$SYSTEM_SERIAL_NUMBER].txt"

	echo -e $verde"Exportando: "$amarillo$PWD"/MAQUINE-[$SYSTEM_SERIAL_NUMBER].txt"$rescolor 	
}

function main(){
	dependence
	getInfoSystem
}

function dependence(){
	## hwinfo
	if ! dpkg -l hwinfo  &> /dev/null ;then
		echo -e "\e[1;31mSe Requiere hwinfo"$rescolor""
		while true; do
			echo "Desea intalar hwinfo"
			echo "                                   "
		echo -e "      "$verde"1)"$rescolor" SI      "
		echo -e "      "$verde"2)"$rescolor" NO      "
		echo "                                       "
		echo -n "      #> "
		read yn
		echo ""
		case $yn in
			1 ) 
				echo -e $verde"Instalando hwinfo"$rescolor
				sudo apt-get install hwinfo -y 
				echo -e $verde"HECHO..."$rescolor
				break ;;
			2 ) salir=1 ; break ;;  
			* ) echo "Opción desconocida. Elige de nuevo";
		  esac
	done
		
	else
		echo -e "\e[1;32mhwinfo Esta Intalado?................SI"$rescolor""
	fi
	sleep 1

	if [ "salir" = "1" ] ; then
		exit 1
	fi
	
}

main
