#!/bin/sh

SASCHA='/usr/share/sascha'
AUX_PWD=$PWD
LIB='sascha-v0.0.1.tar.gz'

if ! [ -d $SASCHA ]; then
	cd /tmp && mkdir scripts-bash && cd scripts-bash

	echo "El directorio no se encuentra se realizara la descarga"
	curl -sL https://github.com/Leo1305Pineda/scripts-bash/raw/master/dist/$LIB -o $LIB
	tar -xvf $LIB
	cp -R sascha $SASCHA
	echo "Lista para usar el script sascha"
	echo "~ $ sascha"

else
	cd $SASCHA && bash $SASCHA/sascha.sh "$@" 
fi

cd $AUX_PWD
if [ -d /tmp/scripts-bash ] ; then 
	rm -r -f /tmp/scripts-bash
fi
